<?php
/**
 * @author andy
 * @email andyworkbase@gmail.com
 * @team MageCloud
 * @package MageCloud_EnhancedEcommerce
 */
?>
<?php
/**
 * GTM noscript template
 *
 * @var \MageCloud\EnhancedEcommerce\Block\GtmCode $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php
/** @var \MageCloud\EnhancedEcommerce\Helper\Data $helper */
$helper = $this->helper(MageCloud\EnhancedEcommerce\Helper\Data::class);
?>
<?= /* @noEscape */ $helper->getGtmNoScriptCode($block->getStore()); ?>
